CREATE TABLE `inventory_management` (
	`p_id` INT(8) NOT NULL AUTO_INCREMENT,
	`p_name` VARCHAR(20) NOT NULL COLLATE 'utf8mb4_unicode_ci',
	`p_price` INT(10) UNSIGNED NOT NULL,
	`p_amount` SMALLINT UNSIGNED NOT NULL,
	`filename` VARCHAR(20) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`filesize` INT(100) UNSIGNED NULL DEFAULT NULL,
	`description` TEXT NULL DEFAULT NULL,
	`manufacturer` VARCHAR(20) NULL DEFAULT NULL,
	`category` VARCHAR(20) NULL DEFAULT NULL,
	`condition` VARCHAR(10) NULL DEFAULT NULL,
	PRIMARY KEY (`p_id`) USING BTREE
)
COLLATE='utf8mb4_unicode_ci'
ENGINE=InnoDB
AUTO_INCREMENT=2
;
